#version: '3.7'

#services:
#  web:
#    container_name: library
#    build: .
#    command: python /usr/src/app/python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/usr/src/app/
#    ports:
#      - 8000:8000
#    env_file:
#      - ./.env.dev

version: "3"
services:
  web:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/code
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"